### ISSUE TITLE
In this the HTML report, some of the car names have been dropped

### ISSUE THREAD

**Issue by markziemann** [kogamanya/bioinfo_exercises#2]
https://github.com/kogamanya/bioinfo_exercises/blob/1e8358fa1748595c56de462eef68976f00190bbd/Bioinfoexercise2.Rmd#L42

The solution is to change the chunk header to increase the fig.height to 8

{r, question2,fig.height=8,fig.width=8}

**Comment by kogamanya** [comment]
Resolved, no more missing car names.
