### ISSUE TITLE
Your code doesn't actually solve the problem here. Try again

### ISSUE THREAD

**Issue by markziemann** [kogamanya/bioinfo_exercises#6]
https://github.com/kogamanya/bioinfo_exercises/blob/1e8358fa1748595c56de462eef68976f00190bbd/Bioinfoexercise4.Rmd#L67

**Comment by kogamanya** [comment]
confuse with the question and will need your assistance

**Comment by markziemann** [comment]
You will need to run this "simulation" many times. For example 10,000 times. 
For each run, you will draw three numbers. (the numbers you can draw are digits 0 to 9).
From that sample, see how frequent it is that you draw the same number 3/3 times

**Comment by markziemann** [comment]
Once you have generated the result of the simulations (called res), then you will need some way to check whether the three numbers in each column are the same
